spring:
  config:
    import: "application_prod.yaml" # communicates to Spring Boot to import the production profile settings
  profiles:
    active: prod # may be overridden by SPRING_PROFILES_ACTIVE

  application:
    name: aces-auth-service
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:aces_auth}_dev"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
logging:
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
  level:
    org.springframework.security: "${SECURITY_LOG_LEVEL:TRACE}"
config:
  app-identity: "aces-auth-service"
  max-sessions: 5
  frontend-url: "${FRONTEND_URL:http://localhost:3000}"
  jwt:
    secret: "${JWT_SECRET:}"
    access-token-expiration: "${JWT_ACCESS_EXPIRATION:3600}" # in seconds (default 1 hour)
    refresh-token-expiration: "${JWT_REFRESH_EXPIRATION:604800}" # in seconds (default 7 days)
  oauth:
    github:
      client-id: "${GITHUB_CLIENT_ID:}"
      client-secret: "${GITHUB_CLIENT_SECRET:}"
    google:
      client-id: "${GOOGLE_CLIENT_ID:}"
      client-secret: "${GOOGLE_CLIENT_SECRET:}"
    discord:
      client-id: "${DISCORD_CLIENT_ID:}"
      client-secret: "${DISCORD_CLIENT_SECRET:}"